version: '3'

services:
  server-a:
    build: ./server1
    ports:
      - '4000:5001'
    volumes:
      - ./server1:/app
    depends_on:
      - server-b
    networks:
      - learning-net

  server-b:
    build: ./server2
    ports:
      - '4001:5002'
    networks:
      - learning-net

networks:
  learning-net:
    driver: bridge
